version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: navyk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ../backend
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/navyk
      REDIS_URL: redis://redis:6379
      JWT_SECRET: devsecret
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
  frontend:
    build: ../frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
  ai:
    build: ../ai
    ports:
      - "8000:8000"
volumes:
  db_data:
